### ISSUE TITLE
[Question] compatibility with Haehnchen/idea-php-laravel-plugin

### ISSUE THREAD

**Issue by vladyslavstartsev** [rentalhost/laravel-insight#26]
Hi!
I have 2 questions for you.
1) Is it compatible with https://github.com/Haehnchen/idea-php-laravel-plugin ?
I mean is there any breaks? If yes, I think you need to mention it.

2) Why don't you just make PRs to https://github.com/Haehnchen/idea-php-laravel-plugin ?

P.S. Is there anything that I can help (not code because I don't know Java, I mean develop and learn it, but the code will look like shit) you with? Not sure that I will (full time, family and etc.), but at least I will try to.

**Comment by rentalhost** [comment]
1. It is compatible, you can use both.
2. It is a pratical study on Java for me. I have done some inspections for [PHP Inspections EA](https://github.com/kalessil/phpinspectionsea) and now I am working on a own plugin to learn more - but lastly I am working in a another project, but I will keep working on it on closest future.

And yes, you can help on it. Now I have more knowledgement on this language, so maybe I can help you with your PRs. Just remember that is important you create tests for any new feature. You can use the DEVELOPERS doc from PHP Inspections EA to you setup your Intellij IDEA (I think that you will need the Ultimate version too).

**Comment by vladyslavstartsev** [comment]
I saw that you're the one of the devs on [PHP Inspections EA](https://github.com/kalessil/phpinspectionsea), that's how I found you and this plugin.

Thanks for fast answer!
